---
- name: Install gitlab-runner
  hosts: gitlab-runner
  become: true
  tasks:
    - name: get install repo file from gitlab
      register: download
      get_url:
        url: https://packages.gitlab.com/install/repositories/runner/gitlab-ci-multi-runner/script.deb.sh
        dest: /tmp/gitlab-runner.deb.sh
        
    - name: run script
      when: download|success
      register: runscript
      shell: bash /tmp/gitlab-runner.deb.sh
      args:
        executable: /bin/bash
      
    - name: install gitlab runner
      when: runscript|success
      apt: name=gitlab-ci-multi-runner state=latest
      
    - name: Docker Machine
      get_url:
        url: https://github.com/docker/machine/releases/download/v0.12.2/docker-machine-Linux-x86_64
        dest: /usr/local/bin/docker-machine
        mode: 0555